// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hometask07._14.data;

#nullable disable

namespace hometask07._14.Migrations
{
    [DbContext(typeof(UserDB))]
    partial class UserDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hometask07._14.model.employee", b =>
                {
                    b.Property<int>("employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("employeeid"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("staffid")
                        .HasColumnType("integer");

                    b.HasKey("employeeid");

                    b.HasIndex("staffid");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("hometask07._14.model.staff", b =>
                {
                    b.Property<int>("staffid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("staffid"));

                    b.Property<string>("staffdescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("staffid1")
                        .HasColumnType("integer");

                    b.Property<string>("staffname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("staffid");

                    b.HasIndex("staffid1");

                    b.ToTable("staffs");
                });

            modelBuilder.Entity("hometask07._14.model.employee", b =>
                {
                    b.HasOne("hometask07._14.model.staff", "staff")
                        .WithMany()
                        .HasForeignKey("staffid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("staff");
                });

            modelBuilder.Entity("hometask07._14.model.staff", b =>
                {
                    b.HasOne("hometask07._14.model.staff", null)
                        .WithMany("staffs")
                        .HasForeignKey("staffid1");
                });

            modelBuilder.Entity("hometask07._14.model.staff", b =>
                {
                    b.Navigation("staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
